name: Dependencies
on:
  schedule:
  - cron: "0 0 * * *"
  push:
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update openconnect version
      run: |
        # export OC_VERSION=$(curl https://gitlab.com/api/v4/projects/openconnect%2Focserv/repository/tags | jq -r '.[0].name')
        export OC_VERSION=1.2.4
        sed -i "s/ENV OC_VERSION=[0-9].[0-9].[0-9]/ENV OC_VERSION=$OC_VERSION/g" Dockerfile

    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Bump ocserv version"
        branch: features/update-dependencies
        title: Bump ocserv version
        labels: dependencies
        delete-branch: true
