name: Dependencies
on:
  schedule:
  - cron: "0 0 * * *"
  push:
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update openconnect version
      id: get_version
      run: |
        # OC_VERSION=$(curl https://gitlab.com/api/v4/projects/openconnect%2Focserv/repository/tags | jq -r '.[0].name')
        OC_VERSION=1.2.4
        sed -i "s/ENV OC_VERSION=[0-9].[0-9].[0-9]/ENV OC_VERSION=$OC_VERSION/g" Dockerfile
        echo "OC_VERSION=$OC_VERSION" >> $GITHUB_OUTPUT

    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Bump ocserv version ${{ steps.get_version.outputs.OC_VERSION }}"
        token: ${{ secrets.PAT }}
        branch: features/update-dependencies
        title: Bump ocserv version
        labels: dependencies
        delete-branch: true
      env:
        OC_VERSION: ${{ steps.get_version.outputs.OC_VERSION }}
